# Generated by Django 4.2.1 on 2023-05-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="cover",
            field=models.ImageField(blank=True, upload_to="tekisite/schools/covers/"),
        ),
        migrations.AlterField(
            model_name="school",
            name="logo",
            field=models.ImageField(blank=True, upload_to="tekisite/schools/logos/"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="profile_pic",
            field=models.ImageField(
                blank=True, null=True, upload_to="tekisite/profile_pics"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="school_logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="tekisite/school_logo"
            ),
        ),
    ]
