# Generated by Django 4.2.1 on 2023-05-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("achievement", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reward",
            name="reward_icon",
            field=models.ImageField(
                blank=True,
                default="reward_images/default.png",
                null=True,
                upload_to="tekiroom/reward_images",
            ),
        ),
    ]
