# Generated by Django 4.1.7 on 2023-05-04 20:13

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Classroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "classroom_code",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("invite_code", models.CharField(max_length=5, unique=True)),
                ("slug", models.SlugField(unique=True)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("tekiroom", "Tekiroom"),
                            ("google_classroom", "Google Classroom"),
                            ("youtube", "Youtube"),
                            ("zoom", "Zoom"),
                            ("google_meet", "Google Meet"),
                            ("microsoft_teams", "Microsoft Teams"),
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                            ("twitch", "Twitch"),
                            ("discord", "Discord"),
                            ("skype", "Skype"),
                            ("vimeo", "Vimeo"),
                            ("webex", "Webex"),
                            ("other", "Other"),
                        ],
                        max_length=255,
                    ),
                ),
                ("platform_url", models.URLField()),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "teachers",
                    models.ManyToManyField(
                        related_name="classrooms_taught", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
