# Generated by Django 4.2.1 on 2023-05-23 16:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homework", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="tekiroom/assignments/"
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="attachment_one",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="tekiroom/submissions/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "doc", "docx", "zip"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="attachment_three",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="tekiroom/submissions/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "doc", "docx", "zip"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="attachment_two",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="tekiroom/submissions/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "doc", "docx", "zip"]
                    )
                ],
            ),
        ),
    ]
